/**
 * The cryptographic stamp.
 *
 * ZATCA specifies ECDSA over secp256k1 with SHA-256 — the Bitcoin curve, not
 * the P-256 that WebCrypto offers. That used to pin invoicing to a Node host,
 * because neither SubtleCrypto nor node:crypto is available on both runtimes.
 *
 * This implementation uses none of them: the curve arithmetic comes from
 * @noble/curves and the key encodings are assembled by hand, so the same code
 * signs an invoice on a Node server and inside a Cloudflare Worker, and
 * produces byte-identical output either way.
 *
 * The encodings match Node's own exporter exactly, which matters more than it
 * sounds: a key generated by an earlier Node deployment must keep working, and
 * a CSID that ZATCA issued against that key must still match it.
 *
 * Keys are generated on the server and never leave it. The private key is
 * stored AES-256-GCM encrypted; whoever holds it can stamp invoices in this
 * branch's name, which is the whole security boundary of e-invoicing.
 */
import { secp256k1 } from '@noble/curves/secp256k1.js';
import { sha256 } from '@noble/hashes/sha2.js';
import {
  encodePkcs8, encodeSpki, fromPem, pointFromSpki, publicPoint, scalarFromPkcs8, toPem,
} from './keys.js';

export interface StampKeyPair {
  /** PKCS#8 PEM — encrypt before storing. */
  privateKeyPem: string;
  /** SubjectPublicKeyInfo DER, base64. Goes into QR tag 8. */
  publicKeyDer: string;
}

/**
 * A fresh stamping identity.
 *
 * The scalar comes from the platform CSPRNG — crypto.getRandomValues, which
 * both runtimes provide — rather than from node:crypto, so a Worker generates
 * keys as safely as a server does.
 */
export function generateStampKeyPair(): StampKeyPair {
  const scalar = Buffer.from(secp256k1.utils.randomSecretKey());
  return {
    privateKeyPem: toPem(encodePkcs8(scalar), 'PRIVATE KEY'),
    publicKeyDer: encodeSpki(scalar).toString('base64'),
  };
}

/** base64 of the raw SHA-256 digest — what ZATCA calls the invoice hash. */
export function invoiceHash(canonicalXml: string): string {
  return Buffer.from(sha256(Buffer.from(canonicalXml, 'utf8'))).toString('base64');
}

/**
 * Sign the document. ZATCA stamps the digest, so the signature verifies
 * against the same value the QR publishes in tag 6.
 */
export function stamp(privateKeyPem: string, canonicalXml: string): Buffer {
  const scalar = scalarFromPkcs8(fromPem(privateKeyPem));
  const digest = sha256(Buffer.from(canonicalXml, 'utf8'));
  // DER-encoded, and prehash:false because the digest is what is passed —
  // omitting it hashes the hash, producing a signature that verifies against
  // nothing and fails only at the authority.
  return Buffer.from(secp256k1.sign(digest, scalar, { format: 'der', prehash: false }));
}

/** Verify a stamp. Used by the tests, and by the chain audit. */
export function verifyStamp(
  publicKeyDer: Buffer, canonicalXml: string, signature: Buffer,
): boolean {
  try {
    const point = publicKeyDer.length === 65 ? publicKeyDer : pointFromSpki(publicKeyDer);
    const digest = sha256(Buffer.from(canonicalXml, 'utf8'));
    // lowS:false because this must accept ANY valid ECDSA signature, not only
    // canonical ones. Signing produces low-S (the modern convention, and what
    // noble emits), but a stamp written by an earlier node:crypto deployment
    // may carry high-S — a perfectly valid signature that ZATCA accepts and a
    // strict verifier silently rejects. Refusing those would fail the chain
    // audit on invoices that are not wrong.
    return secp256k1.verify(signature, digest, point, {
      format: 'der', prehash: false, lowS: false,
    });
  } catch {
    return false;
  }
}

export function publicKeyDerFromPrivate(privateKeyPem: string): Buffer {
  return encodeSpki(scalarFromPkcs8(fromPem(privateKeyPem)));
}

/** The raw uncompressed point, for a caller that wants the key itself. */
export function publicPointFromPrivate(privateKeyPem: string): Buffer {
  return publicPoint(scalarFromPkcs8(fromPem(privateKeyPem)));
}

/**
 * The certificate signature for QR tag 9. A real one comes from the CSID ZATCA
 * issues; before onboarding there is none, and this returns undefined so the
 * tag is omitted rather than filled with something untrue.
 */
export function certificateSignature(certificateBase64: string | null): Buffer | undefined {
  if (!certificateBase64) return undefined;
  const der = Buffer.from(certificateBase64.replace(/-----[^-]+-----|\s/g, ''), 'base64');
  return extractSignatureBits(der) ?? undefined;
}

/** Minimal DER walk: Certificate ::= SEQUENCE { tbs, algid, signature BIT STRING } */
function extractSignatureBits(der: Buffer): Buffer | null {
  let i = 0;
  const readLength = (): number => {
    const first = der[i++]!;
    if (first < 0x80) return first;
    const count = first & 0x7f;
    let len = 0;
    for (let n = 0; n < count; n++) len = (len << 8) | der[i++]!;
    return len;
  };
  if (der[i++] !== 0x30) return null;          // Certificate SEQUENCE
  readLength();
  for (let field = 0; field < 3; field++) {
    const tag = der[i++]!;
    const len = readLength();
    if (field === 2) {
      if (tag !== 0x03) return null;           // BIT STRING
      // First content byte is the count of unused bits; skip it.
      return der.subarray(i + 1, i + len);
    }
    i += len;
  }
  return null;
}
